name: Build and deploy Python project to Azure Function App - sdk-bindings-example

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "." # set this to the path to your web app project, defaults to the repository root
  PYTHON_VERSION: "3.11" # set this to the python version to use

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install function tools
        run: sudo apt-get install azure-functions-core-tools-4 -y

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D6A1AC4DA4414DD8A2D6F8B7EBF95881 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1C07ACD535694296B90F2E80B2FE9DCA }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4674FE39923C46F2B28889E631EEBC66 }}

      - name: Deploy
        run: func azure functionapp publish sdk-bindings-example --build-remote --python
